# Generated by Django 2.2.3 on 2020-01-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200127_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='boys_pop',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='constituency',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='county',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fb',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='girls_pop',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=555),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='other',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postaladdress',
            field=models.CharField(blank=True, max_length=555),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, max_length=555),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school_gender',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school_type',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subcounty',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='teachers_pop',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=555),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_pop',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ward',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
